# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stanford MAST Lab
email: kozyraki@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  "The Stanford Multi-scale Architectures & Systems Team"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mast.stanford.edu" # the base hostname & protocol for your site, e.g. http://example.com
logo: /imgs/logo.png
github_username:  stanford-mast

collections:
  pubs:
    output: true
    permalink: /pubs/:slug/index.html
  blogs:
    output: true
    permalink: /blogs/:slug/index.html

defaults:
  - scope:
      path: ""
      type: blogs
    values:
      layout: blog
      stub: true
      type: paper
  - scope:
      path: ""
      type: pubs
    values:
      layout: pub
      stub: true
      type: paper

# Build settings
sass:
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-scholar
  - jekyll-sitemap

# For latex support
markdown: kramdown

# Dates are used to sort publications, and we will likely upload
# publications before their conferences occur.
future: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - package-lock.json
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # From old website infra
  - src/
  - static/
  - scripts/
